baseURL = "https://paulbenoit.com/"
languageCode = "en-us"
title = "Paul Benoit | Cyber Security, Software, and Other Things"
theme = "mytheme"
relativeURLs = true
pygmentsCodeFences = true
pygmentsUseClasses = true

googleAnalytics = "UA-167697355-1"

[menu]
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/paul_benoit_resume.pdf"
    weight = 100

  [[menu.main]]
    identifier = "bookshelf"
    name = "Bookshelf"
    url = "/bookshelf"
    weight = 120

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 120
