## Basic Configuration

## old NS lookup servers
## ns13.domaincontrol.com
## ns14.domaincontrol.com


#baseurl = "test.com"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Paul Benoit"
title = "Paul Benoit"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Paul Benoit"
intro = "Security & Development"
description = "Currently making DFIR tools for The Crypsis Group."
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Cyber Paul Benoit"
keywords = "benoit,paul,security,cyber,developer"

## Social Accounts
[params.social]
github = "thepaulbenoit"
linkedin = "paulbenoitsecurity"
email = "benoitpaul6@gmail.com"

## Extras
[params.extra]
copyright = "© 2019. Paul Benoit. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = false
highlightjs = true
socialmarkup = true

## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "resume"
    identifier = "resume"
    weight = 200
    url = "/paul_benoit_resume.pdf"
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"