baseURL = "http://example.org/"
languageCode = "en-us"
title = "Paul Benoit"
theme = "mytheme"
relativeURLs = true
pygmentsCodeFences = true
pygmentsUseClasses = true

googleAnalytics = "UA-167697355-1"

[Social]
  twitter = "thepaulbenoit"

[menu]
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/paul_benoit_resume.pdf"
    weight = 100

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 120


    